@startuml
start
:Создание начальной популяции;
:Оценка приспособленности;

repeat
  :Отбор;
  :Кроссинговер;
  :Мутация;
  :Оценка приспособленности новых индивидов;
  :Создание новой популяции;
  
  if (Условия останова выполняются?) then (Да)
    break
  else (Нет)
  endif
  
repeat while (Истинно) is (да)

:Выбор наилучшего индивида;
stop
@enduml