@startuml
start
:Получение экспертных оценок вероятностей;
:Расчет вероятности выбора квектора компьютерной атаки;
:Расчет вероятностей возникновения ложных, излишних и отказов в срабатывании;
:Сопоставление выключателей и воздействующих на них устройств защиты и 
управления;
fork
  :Расчет вероятности отказа в срабатывании основных, основных и резервных 
  защит шин и трансформаторов;
  :Расчет математического ожидания увеличения стоимости ремонта 
  оборудования;
  :Расчет суммарного математического ожидания увеличения стоимости ремонта оборудования;
fork again
  :Определение вероятности отключения каждого выключателя;
  :Выявление режимных ситуаций, при которых может возникнуть недоотпуск 
  электроэнергии;
  :Расчет вероятности появления выявленных режимных ситуаций, на основе 
  вероятностей отключения отдельных выключателей;
  :Расчет математического ожидания недоотпуска электроэнергии для каждого 
  выявленного режима;
  :Расчет суммарного недоотпуска электроэнергии на основе суммы математических 
  ожиданий недоотпуска электроэнергии;
end fork
:Экономический ущерб от ненадежности;
stop
@enduml