@startuml

|Моделирующий комплекс|
start
:Проектирование структурных схем ВАПС;
:Описание вторичных подсистем;

|#AntiqueWhite|СППР|
repeat
  :Задание ограничений;
repeatwhile (<b>Решение существует?) is (нет) not (да)

:Генерация первичной популяции;

|Моделирующий комплекс|
:Расчет недоотпуска электроэнергии;

|#AntiqueWhite|СППР|
:Расчет экономического ущерба от недоотпуска
электроэнергии;

repeat
    |#AntiqueWhite|СППР|
    :Генерация новой популяции;

    |Моделирующий комплекс|
    :Расчет недоотпуска электроэнергии;

    |#AntiqueWhite|СППР|
    :Расчет экономического ущерба от недоотпуска
    электроэнергии;
repeatwhile (<b>Условия останова выполняются?) is (нет) not (да)


|СППР|
:Формирование проектного решения;
stop

@enduml